### ISSUE TITLE
R CMD check NOTEs

### ISSUE THREAD

**Issue by hadley** [jbryer/PSAboot#1]
I'm seeing:

```
checking R code for possible problems ... NOTE
boxplot.PSAboot: no visible global function definition for
  ‘geom_tufteboxplot’
```

Which you can probably fix with `foo::bar()` style

And

```
checking data for non-ASCII characters ... NOTE
  Note: found 4 marked UTF-8 strings
```

which I don't _think_ is important, but I'm not sure

**Comment by jbryer** [comment]
Thanks Hadley. Better late then never I suppose. PSAboot is back on CRAN.

**Comment by hadley** [comment]
FWIW currentl-Hadley knows that you can definitely ignore the second note 😄

**Comment by jbryer** [comment]
Thanks. I avoided CRAN for many years but I have to say the process is so much better, in part because of devtools (thank you!) and also when I got something wrong the responses were helpful and I don't feel attacked. Not sure if you had anything to do with that, if you did, thanks.
